name: Test workflow

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  test-job:
    name: Test job
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Test step
        uses: silverstripe/gha-issue@v1
        with:
          title: Test issue
          description: |
            This is an issue
